"""Init

Revision ID: d4786b2ef7f8
Revises: 7913c7eada43
Create Date: 2021-11-07 18:50:20.072490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4786b2ef7f8'
down_revision = '7913c7eada43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('union_member', sa.Column('token', sa.String(length=256), nullable=True))
    op.add_column('union_member', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('union_member', 'password')
    op.drop_column('union_member', 'token')
    # ### end Alembic commands ###
